### ISSUE TITLE
Skip backup of Google Music cached data

### ISSUE THREAD

**Issue by zman0900** [TeamWin/Team-Win-Recovery-Project#111]
I use google music a lot, so it tends to take up a lot of space.  Having a phone without expandable storage (Nexus 4) means google music stores its files in /data/data/com.google.android.music instead of in /sdcard, so each backup has to make a copy of those files.  Since this is just cached data, it doesn't really need to be backed up.  It would be very useful to me if there were an option to exclude it from backups, at least on phones where /data is not backed up as an image.

**Comment by ameer1234567890** [comment]
FYI - This is already the default behavior in the "other" popular custom recovery.

**Comment by swrobel** [comment]
:+1:

**Comment by garethrepton** [comment]
This behaviour would be very useful. Perhaps as a slightly more generic solution, an option to exclude some apps from the Nandroid backups completely would be better/easier? Not sure how technically feasible this is, but it would definitely be useful when backing up.

**Comment by zman0900** [comment]
What about a file that could be place somewhere like /sdcard/TWRP/exclude.lst and contain a list of files or directories to exclude from the backup of /data?  Obviously this wouldn't work on devices that do an image based backup, but for others it shouldn't be too hard to implement, considering there must already be a way of choosing specific files for each archive to split into multiple volumes, and tar has the --exclude flag.

**Comment by PaulMEdwards** [comment]
@zman0900 has the right idea... Allow the user to manage their own excludes using a file which contains Regular Expressions.

**Comment by bigbiff** [comment]
This is implemented by default in TWRP now.

**Comment by jumperalex** [comment]
How do I make that happen?  I'm on 2.6.3.1 on a Toroplus but it still seems to want to backup the full /data partition and is now telling me there is not enough room to backup.  There would be if it was skipping the music.

**Comment by bigbiff** [comment]
How do you know it's from not skipping google music cache?

**Comment by jumperalex** [comment]
Under Setting|Storage the phone has
28.13 Total Space
8.85 GB free
12.5GB in Apps (app data and media content) of which Google Play music takes up 11.33GB

When i go into TWRP and start a backup, it lists /data as needing about ~12GB (from memory) and of course will not backup due to insufficient space.

For completeness i unpinned all of my music, went back into TWRP, it now says /data is 1.2GB and of course between the smaller /data partition and the extra free space (19GB) the backup proceeds as expected.

That tells me it is not skipping music

**Comment by jumperalex** [comment]
And now with all music repinned, trying to run a backup i get "not enough space."

Is there anything i can provide to help detail the issue further?

**Comment by bigbiff** [comment]
Reopened because we are not skipping the directory in check folder size function. I am working on an implementation.

**Comment by jumperalex** [comment]
Sounds great.  Thanks so much.  I really do prefer TWRP.

**Comment by Dees-Troy** [comment]
This has been fixed.

**Comment by jcwenger** [comment]
TWRP 2.7.0.0 hammerhead from http://techerrata.com/file/twrp2/hammerhead/openrecovery-twrp-2.7.0.0-hammerhead.img, tested on a Nexus 5 32GB, does not properly exclude pinned Google music.
/data partition (on my device) shows in the TWRP backup menu as 20GB (18.95GB of this is Google Play Music).
swiping complains about lack of free space and aborts.

**Comment by ntowl24** [comment]
This issue still remains in TWRP 2.7.1.1 on the Nexus 5 (hammerhead). I've tested this immediately after flashing a fresh image on the 16GB version.

**Comment by jcwenger** [comment]
Resolved, for me, on my 32G Nexus 5 using TWRP 2.7.1.1 for hammerhead (8091a4d1b1bddc442be7f76982be1e67)

**Comment by GohToh** [comment]
I am on 2.8.6.0 and the issue is still there. 

Would be really nice if we're able to exclude this folder. This should be the standard in my opinion.

**Comment by ciarpame** [comment]
I am on 3.0.2 and the issue is still there for me too, several GBs of unuseful music backup is wasting my storage space.
I could pay a premium price for such a feature.

**Comment by sanwalah** [comment]
TWRP 2.8.3.1 on LG G2
data is almost 17 GB, can't backup on single otg drive of 16 GB.
Can it (my current twrp or any later version) backup on multiple otg drives one by one like creating multiple volumes?
