### ISSUE TITLE
LG G6 (H870) /system is busy (-1)

### ISSUE THREAD

**Issue by Smasher1974** [TeamWin/Team-Win-Recovery-Project#1133]
When I update my LineageOS version always the following issue appears...
"/system is busy (-1)"
This issue appeas using TWRP version 3.2.1-0 and 3.1.1-0.
Pls. can you fix this issue soon?

**Comment by APachLv** [comment]
Got the same issue.

**Comment by Smasher1974** [comment]
no feedback from TWRP team :-(
will this issue be fixed in the next official version or is a beta available with a fix?

**Comment by CaptainThrowback** [comment]
You should contact your maintainer via the support thread on XDA. Posting here is really for upstream issues, not device-specific problems.

EDIT: That being said, if your maintainer disables the Debug flags in his BoardConfig, it should fix this problem.

**Comment by Smasher1974** [comment]
the issue was fixed in "Melina TWRP v3.2.1 rel3" version.
https://forum.xda-developers.com/lg-g6/development/recovery-twrp-3-2-1-unofficial-fixes-t3722199
I installed this TWRP version middle of last week and then I updated LineageOS  to latest March build manually (enter TWRP, choose "INSTALL" and so on) and there was no error message.

**Comment by Smasher1974** [comment]
I installed latest official TWRP version 3.2.2-0 (h870) yesterday and the issue still exists.
So the old and the new is not recommended to use by LineageOS users.
But... the issue is fixed in unofficial build "Melina TWRP v3.2.1", URL https://forum.xda-developers.com/lg-g6/development/recovery-twrp-3-2-1-unofficial-fixes-t3722199.
Why official TWRP team is not able to provide a fixed version???

**Comment by CaptainThrowback** [comment]
This isn't about the "TWRP Team", this is about the "device maintainer". The core TWRP team is just 2 people, and there are over 100 devices that are supported. As I already stated, you need to contact your device maintainer to submit the update/fix to the TWRP Gerrit, and have an updated device build run.
