### ISSUE TITLE
[crespo] Can't flash zip through goo manager after upgrading to JB

### ISSUE THREAD

**Issue by samcorbin** [TeamWin/Team-Win-Recovery-Project#22]
JB seems to mount sdcard as /storage/sdcard0. So whenever I'm trying to flash through goomanager, goomanager uses that location, but TWRP is still using /storage/sdcard, which causes TWRP unable to find the zip. But sdcard is still able to mount in TWRP and I'm still able to flash from TWRP.
Below is the log:

```
-- Install /storage/sdcard0/goomanager/rom.zip
Finding update package...
E: unknown volume for path [/storage/sdcard0/goomanager/rom.zip]
E: Can't mount /storage/sdcard0/goomanager/rom.zip
* Verifying filesystem...
* Verifying partition sizes...
E: Error instaling zip file '/storage/sdcard0/goomanager/rom.zip'
Done processing script file
```

**Comment by PaulMEdwards** [comment]
I've also experienced this on my wife's Nook Tablet running this JB ROM w/TWRP 2.1:
http://forum.xda-developers.com/showthread.php?t=1773362

**Comment by samcorbin** [comment]
kinda baffle why would JB change the mount point. If I modify vold.fstab mount point from /storage/sdcard0 to /storage/sdcard, after reboot, my phone stuck at boot animation.

**Comment by bigbiff** [comment]
There is an impending goomanager update that should fix this problem. Not sure of ETA but I will post back when I find out.

**Comment by Kage1** [comment]
I'm not sure if this is related but on my Atrix 4G, Olympus, I try to flash TWRP and it say's it's installed, but when I reboot into recovery the stock CWM recovery is still present.  Haven't tried to to flash it via fastboot. Running CM 7.2 final.

**Comment by bigbiff** [comment]
Are you able to use dd on the Atrix 4g to flash recovery?

**Comment by Kage1** [comment]
Never was able to flash it through the goo manager. I flashed it last night using fastboot and that worked with no problems.

**Comment by Kage1** [comment]
Read your comment again and I realized I read the comment wrong. What is dd short for?

**Comment by bigbiff** [comment]
dd is a gnu utility that writes raw image files to a block device.

**Comment by samcorbin** [comment]
found a temporary solution to this. set '/sdcard/goomanager/' as download path in goomanager.

**Comment by sawy3r** [comment]
That worked, thanks samcorbin!

**Comment by Dees-Troy** [comment]
New version of GooManager was released yesterday which should alleviate this problem.

**Comment by azrash** [comment]
hi, i am not sure whether to re open this or submit a new error. but flashing zip files via GooManager app didnt work for me. 

it will just reboot to TWRP and stay like that.i have to manually select which zip files to flash again from the recovery.

I am using twrp v2.3.3.3
latest goomanager from play store
on mako nexus 4
superSU
