### ISSUE TITLE
Can't decrypt data partition LG H811 3.0.0.0

### ISSUE THREAD

**Issue by mrbox24** [TeamWin/Team-Win-Recovery-Project#606]
Hey guys, I had a problem with TWRP not mounting data partition after encrypting. Took awhile but I finally got TWRP to just format the encrypted partition. I didn't set a password at first, didn't know what to put in for TWRP having not set anything, set a pin, password, pattern, TWRP wouldn't take it. What did I do wrong? Was it not knowing a default password the first run? How does it work? Another thing I've noticed is not to back up a ROM with a pattern set as it won't survive a restore. Luckily the stock ROM had a pin fallback after so many knock code attempts that worked or I would have been in a mess, ha ha.

I'm sure I'm missing something here...

Thanks for reading...

**Comment by objecttothis** [comment]
I can confirm this problem on H811 running CM13 and TWRP 3.0.0.0.  After device encryption and reboot into TWRP the password fails even though it is successful in the normal booting process.

**Comment by Rui-Santos** [comment]
Have you guys tried to mount the system partition before trying the decryption? I have a similar problem on Moto E and it decrypts if I cancel the password prompt, go to Mount and mount the system partituon and then click Decrypt Data. It will then accept the password and decrypt successfully.
But then you will not be able to flash anything to /system because it gets mounted read only and can't be unmounted because some files are open.

**Comment by objecttothis** [comment]
Tried it, but no dice.  I tap the check boxes next to the System Partition and External SD card, then tap decrypt Data partition and get the same error.

**Comment by draggehn** [comment]
@objecttothis I had the same problem on my Nexus 5X (bullhead). I fixed it by selecting EVERYTHING except OTG in mount and entering the password. At least, that seems to have been what fixed it.

**Comment by objecttothis** [comment]
@septemus thank you for the suggestion.  Just tried it, but that also does not work.  Even if it did, it would only be a workaround.

**Comment by objecttothis** [comment]
This is still an issue in 3.0.2-0

**Comment by ihor-sviziev** [comment]
Looks like fix already merged. More details here: https://github.com/TeamWin/android_device_oneplus_bacon/issues/10 

Waiting for 3.0.3 for all devices

**Comment by ihor-sviziev** [comment]
@Dees-Troy could you build new recovery version with decryption fix patch for all devices (really needed for OnePlus 2)

**Comment by objecttothis** [comment]
@ihor-sviziev any idea on when 3.0.3 might be distributed for H811?

**Comment by ihor-sviziev** [comment]
@objecttothis I have no ideas. Also I'm waiting fixed recovery version for OnePlus 2. :disappointed:

**Comment by Stokel** [comment]
Is there maybe an ETA for new builds (need Galaxy S4; i9506) with this fix, it has been a while now...

**Comment by ankuragarwal1982** [comment]
Is the fix available now ? I faced this problem today!

**Comment by QuinnLion** [comment]
This issue persists on 3.1.0-0 as well.
https://pastebin.mozilla.org/8982604
Fails with system mounted rw as well.

**Comment by steadfasterX** [comment]
Go to the official H811/H815 TWRP thread and ask there for support on this. You will have to try the latest BETA provided their as well.

**Comment by steadfasterX** [comment]
@bigbiff please close. This has been fixed since 3.1.x
